// Sushi menu card set (2026-09). Swap CARDS/CARD_SET whenever the item list
// changes — card_set is stored per submission so old and new data never mix
// in aggregates. Images live in assets/Fotos do itens/ (folder name and some
// filenames contain spaces/accents, so cardImageSrc() below runs them through
// encodeURI before use in an <img src>).
const CARD_SET = 'sushi-menu-v1';
const CARDS = [
  { id: '01', label: "Ceviche", image: "assets/Fotos do itens/1 Ceviche.webp" },
  { id: '02', label: "Camarão Empanado", image: "assets/Fotos do itens/2 Camarão Empanado.jpg" },
  { id: '03', label: "California Roll", image: "assets/Fotos do itens/3 California Roll.png" },
  { id: '04', label: "Hot philadelphia roll", image: "assets/Fotos do itens/4 Hot philadelphia roll.webp" },
  { id: '05', label: "Philadelphia roll", image: "assets/Fotos do itens/5 Philadelphia roll.jpg" },
  { id: '06', label: "Roll de salmão", image: "assets/Fotos do itens/6 Roll de salmão.webp" },
  { id: '07', label: "Roll de atum", image: "assets/Fotos do itens/7 Roll de atum.webp" },
  { id: '08', label: "Uramaki de salmão", image: "assets/Fotos do itens/8 Uramaki de salmão.webp" },
  { id: '09', label: "Uramaki ebi", image: "assets/Fotos do itens/9 Uramaki ebi.png" },
  { id: '10', label: "Katsu curry", image: "assets/Fotos do itens/10 Katsu curry.jpg" },
  { id: '11', label: "Temaki philadelphia", image: "assets/Fotos do itens/11 Temaki philadelphia.jpg" },
  { id: '12', label: "Temaki hot philadelphia", image: "assets/Fotos do itens/12 Temaki hot philadelphia.jpg" },
  { id: '13', label: "Temaki de camarão", image: "assets/Fotos do itens/13 Temaki de camarão .jpg" },
  { id: '14', label: "Temaki de salmão skin", image: "assets/Fotos do itens/14 Temaki de salmão skin.jpg" },
  { id: '15', label: "Temaki de salmão", image: "assets/Fotos do itens/15 Temaki de salmão.webp" },
  { id: '16', label: "Sushi de salmão", image: "assets/Fotos do itens/16 Sushi de salmão.webp" },
  { id: '17', label: "Sushi de atum", image: "assets/Fotos do itens/17 Sushi de atum.webp" },
  { id: '18', label: "Sushi de peixe branco", image: "assets/Fotos do itens/18 Sushi de peixe branco.webp" },
  { id: '19', label: "Sushi de haddock", image: "assets/Fotos do itens/19 Sushi de haddock.jpg" },
  { id: '20', label: "Sushi de polvo", image: "assets/Fotos do itens/20 Sushi de polvo.jpg" },
  { id: '21', label: "Sushi salmon skin", image: "assets/Fotos do itens/21 Sushi salmon skin.jpg" },
  { id: '22', label: "Sashimi de salmão", image: "assets/Fotos do itens/22 Sashimi de salmão.webp" },
  { id: '23', label: "Sashimi de atum", image: "assets/Fotos do itens/23 Sashimi de atum.webp" },
  { id: '24', label: "Sashimi de peixe branco", image: "assets/Fotos do itens/24 Sashimi de peixe branco.webp" },
  { id: '25', label: "Sashimi de haddock", image: "assets/Fotos do itens/25 Sashimi de haddock.jpg" },
  { id: '26', label: "Sashimi de polvo", image: "assets/Fotos do itens/26 Sashimi de polvo.jpg" },
  { id: '27', label: "Yakisoba de carne", image: "assets/Fotos do itens/27 Yakisoba de carne.webp" },
  { id: '28', label: "Yakisoba de frango", image: "assets/Fotos do itens/28 Yakisoba de frango.webp" },
  { id: '29', label: "Tonkatsu", image: "assets/Fotos do itens/29 Tonkatsu.jpg" },
  { id: '30', label: "Lámen de porco", image: "assets/Fotos do itens/30 Lámen de porco.webp" },
  { id: '31', label: "Lámen vegano", image: "assets/Fotos do itens/31 Lámen vegano.jpg" },
  { id: '32', label: "Misoshiru", image: "assets/Fotos do itens/32 Misoshiru.webp" },
  { id: '33', label: "Edamame", image: "assets/Fotos do itens/33 Edamame.webp" },
  { id: '34', label: "Sunomono", image: "assets/Fotos do itens/34 Sunomono.jpg" },
  { id: '35', label: "Gyoza de porco", image: "assets/Fotos do itens/35 Gyoza de porco.png" },
  { id: '36', label: "Gyoza de legumes", image: "assets/Fotos do itens/36 Gyoza de legumes.jpg" },
  { id: '37', label: "Harumaki de legumes", image: "assets/Fotos do itens/37 Harumaki de legumes.webp" },
  { id: '38', label: "Harumaki de queijo", image: "assets/Fotos do itens/38 Harumaki de queijo.jpg" },
  { id: '39', label: "Harumaki de chocolate", image: "assets/Fotos do itens/39 Harumaki de chocolate.jpg" },
  { id: '40', label: "Harumaki de camarão", image: "assets/Fotos do itens/40 Harumaki de camarão.webp" },
  { id: '41', label: "Onigiri philadelphia", image: "assets/Fotos do itens/41 Onigiri philadelphia .jpg" },
  { id: '42', label: "Onigiri tuna mayo", image: "assets/Fotos do itens/42 Onigiri tuna mayo.jpg" },
  { id: '43', label: "Onigiri berinjela", image: "assets/Fotos do itens/43 Onigiri berinjela.jpg" },
  { id: '44', label: "Combinado 15 peças", image: "assets/Fotos do itens/44 Combinado 15 peças.jpg" },
  { id: '45', label: "Combinado 30 peças", image: null },
  { id: '46', label: "Combinado 45 peças", image: "assets/Fotos do itens/46 Combinado 45 peças.jpg" },
  { id: '47', label: "Combinado 60 peças", image: "assets/Fotos do itens/47 Combinado 60 peças.jpg" },
  { id: '48', label: "Monte seu poke", image: "assets/Fotos do itens/48 Monte seu poke.png" },
  { id: '49', label: "Poke de camarão", image: "assets/Fotos do itens/49 Poke de camarão.jpg" },
  { id: '50', label: "Coca-Cola", image: "assets/Fotos do itens/50 Coca-Cola.webp" },
  { id: '51', label: "Coca-Cola zero", image: "assets/Fotos do itens/51 Coca-Cola zero.webp" },
  { id: '52', label: "Sprite", image: "assets/Fotos do itens/52 Sprite.png" },
  { id: '53', label: "Guaraná", image: "assets/Fotos do itens/53 Guaraná.webp" },
  { id: '54', label: "Mate da casa", image: "assets/Fotos do itens/54 Mate da casa.webp" },
];
